title: River Tournaments PDX
description: Official site for Weekly Pool Tournaments at River Pool & Sports Bar in Downtown Portland Oregon
markdown: kramdown
permalink: pretty
baseurl: "" # Correct because it's deployed to domain root
url: "https://rivertournaments.com"

plugins:
  - jekyll-sitemap
