title: River Tournaments
description: Official site for River Tournament hosted by Andy Morschl
markdown: kramdown
permalink: pretty
baseurl: "" # Correct because it's deployed to domain root
url: "https://rivertournaments.com"

plugins:
  - jekyll-sitemap
